import { Product, Category, Review, Coupon } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Wedding Cakes",
    slug: "wedding",
    image: "https://images.unsplash.com/photo-1562777717-dc6984f65a63?auto=format&fit=crop&w=800&q=80",
    itemCount: 14,
    description: "Grand multi-tiered haute couture wedding masterpieces crafted with edible gold leaf and handcrafted sugar flowers.",
  },
  {
    id: "cat-2",
    name: "Birthday Cakes",
    slug: "birthday",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
    itemCount: 22,
    description: "Opulent celebration cakes customized with personalized chocolate sails, fresh berries, and metallic accents.",
  },
  {
    id: "cat-3",
    name: "Anniversary Cakes",
    slug: "anniversary",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    itemCount: 18,
    description: "Romantic velvet, champagne-infused frostings, and delicate spun sugar sculptures for timeless love.",
  },
  {
    id: "cat-4",
    name: "Cupcakes & Mini Bites",
    slug: "cupcakes",
    image: "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=800&q=80",
    itemCount: 30,
    description: "Bite-sized artisanal cupcakes piped with Valrhona ganache and French meringue buttercream.",
  },
  {
    id: "cat-5",
    name: "Photo Cakes",
    slug: "photo-cakes",
    image: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=800&q=80",
    itemCount: 12,
    description: "High-definition edible sugar prints embedded on silky buttercream bases.",
  },
  {
    id: "cat-6",
    name: "French Pastries",
    slug: "pastries",
    image: "https://images.unsplash.com/photo-1603532648955-039310d9ed75?auto=format&fit=crop&w=800&q=80",
    itemCount: 25,
    description: "Traditional Parisian Mille-Feuille, Eclairs, Tarts, and Macaron towers made fresh daily.",
  },
  {
    id: "cat-7",
    name: "Brownies & Truffles",
    slug: "brownies",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    itemCount: 16,
    description: "Rich 70% Dark Belgian chocolate fudgy brownies with sea salt caramel and gold dust.",
  },
  {
    id: "cat-8",
    name: "Baby Shower",
    slug: "baby-shower",
    image: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?auto=format&fit=crop&w=800&q=80",
    itemCount: 10,
    description: "Whimsical pastel-themed creations with handmade sugar teddy bears and delicate fondant clouds.",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "cake-1",
    name: "The Royal 24K Gold Crown",
    slug: "royal-24k-gold-crown",
    price: 3499,
    offerPrice: 2999,
    rating: 4.9,
    reviewsCount: 128,
    description: "Our signature luxury cake layered with 70% Belgian Dark Chocolate Truffle, Madagascar Bourbon Vanilla sponge, coated in deep burgundy buttercream and finished with edible 24-Karat gold leaf.",
    shortDesc: "Belgian Dark Truffle with 24K Edible Gold Leaf & Burgundy Glaze.",
    category: "Wedding",
    eggless: true,
    flavors: ["Belgian Dark Chocolate", "Swiss Salted Caramel", "Red Velvet Cream Cheese"],
    weights: ["1 kg", "2 kg", "3 kg", "5 kg"],
    images: [
      "https://images.unsplash.com/photo-1562777717-dc6984f65a63?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["Featured", "Best Seller", "Trending"],
    isFeatured: true,
    isBestSeller: true,
    ingredients: ["Belgian Chocolate 70%", "Organic Flour", "Madagascar Vanilla Bean", "Edible 24K Gold Leaf", "Fresh French Cream"],
    stock: true,
  },
  {
    id: "cake-2",
    name: "Velvet Rose & Champagne Symphony",
    slug: "velvet-rose-champagne",
    price: 2899,
    offerPrice: 2499,
    rating: 4.95,
    reviewsCount: 94,
    description: "Decadent Red Velvet layers infused with non-alcoholic pink champagne soak, real organic rose petal preserve, and silky mascarpone frosting.",
    shortDesc: "Infused Red Velvet with Organic Rose Petals & Champagne Frosting.",
    category: "Anniversary",
    eggless: true,
    flavors: ["Red Velvet Rose", "Strawberry Vanilla Bean", "Champagne Raspberry"],
    weights: ["0.5 kg", "1 kg", "2 kg"],
    images: [
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["Best Seller", "Trending"],
    isFeatured: true,
    isBestSeller: true,
    ingredients: ["Cocoa Butter", "Mascarpone Cheese", "Organic Rose Water", "Fresh Raspberry Compote"],
    stock: true,
  },
  {
    id: "cake-3",
    name: "Golden Ferrero Hazelnut Elegance",
    slug: "golden-ferrero-hazelnut",
    price: 2599,
    offerPrice: 2299,
    rating: 4.88,
    reviewsCount: 110,
    description: "Crunchy roasted hazelnut praline layers drizzled with Nutella ganache, covered in crushed Ferrero Rocher and metallic gold dust accents.",
    shortDesc: "Roasted Hazelnut Praline, Nutella Ganache & Ferrero Rocher Topping.",
    category: "Birthday",
    eggless: false,
    flavors: ["Ferrero Hazelnut Crunch", "Chocolate Fudge", "Espresso Praline"],
    weights: ["1 kg", "2 kg", "3 kg"],
    images: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1562777717-dc6984f65a63?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["Best Seller"],
    isFeatured: true,
    isBestSeller: true,
    ingredients: ["Piedmont Hazelnuts", "Valrhona Cocoa", "Butter", "Ferrero Rocher Chocolates"],
    stock: true,
  },
  {
    id: "cake-4",
    name: "Opulent Berry Pistachio Bloom",
    slug: "opulent-berry-pistachio",
    price: 3199,
    offerPrice: 2799,
    rating: 4.92,
    reviewsCount: 76,
    description: "Sicilian pistachio sponge paired with fresh wild blueberry reduction, white chocolate mousse, and edible violet flowers.",
    shortDesc: "Sicilian Pistachio Sponge with Wild Blueberry Reduction.",
    category: "Wedding",
    eggless: true,
    flavors: ["Sicilian Pistachio Blueberry", "Matcha White Chocolate", "Lemon Berry Burst"],
    weights: ["1 kg", "2 kg", "4 kg"],
    images: [
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["Featured", "New"],
    isFeatured: true,
    isBestSeller: false,
    ingredients: ["Sicilian Pistachios", "Fresh Blueberries", "Belgian White Chocolate", "Organic Eggless Base"],
    stock: true,
  },
  {
    id: "cake-5",
    name: "Midnight Lotus Biscoff Deluxe",
    slug: "midnight-lotus-biscoff",
    price: 2399,
    offerPrice: 1999,
    rating: 4.85,
    reviewsCount: 89,
    description: "Layered Belgian speculoos cookie crust with spiced Biscoff cream cheese mousse, caramelized biscuit drip, and roasted almond flakes.",
    shortDesc: "Lotus Biscoff Spiced Cream Cheese Mousse & Caramel Drip.",
    category: "Birthday",
    eggless: true,
    flavors: ["Lotus Biscoff Cream", "Salted Caramel Speculoos"],
    weights: ["0.5 kg", "1 kg", "2 kg"],
    images: [
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["Trending"],
    isFeatured: false,
    isBestSeller: true,
    ingredients: ["Lotus Biscoff Spread & Biscuits", "Cream Cheese", "Heavy Cream", "Toasted Almonds"],
    stock: true,
  },
  {
    id: "cake-6",
    name: "Celestial Macaron Tower Cake",
    slug: "celestial-macaron-tower",
    price: 4299,
    offerPrice: 3899,
    rating: 4.98,
    reviewsCount: 52,
    description: "An extraordinary 3-tier celebration cake adorned with handcrafted French macarons in rose gold, vanilla, and salted caramel flavors.",
    shortDesc: "Multi-tiered celebration cake topped with Parisian Macarons.",
    category: "Wedding",
    eggless: false,
    flavors: ["Vanilla Bean Macaron", "Raspberry White Chocolate"],
    weights: ["2 kg", "3 kg", "5 kg"],
    images: [
      "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1603532648955-039310d9ed75?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["Featured", "Trending"],
    isFeatured: true,
    isBestSeller: false,
    ingredients: ["Almond Flour", "Egg Whites", "French Butter", "Organic Jam", "Gold Leaf"],
    stock: true,
  },
  {
    id: "cake-7",
    name: "Enchanted Garden Butterfly Box",
    slug: "enchanted-garden-butterfly",
    price: 2799,
    offerPrice: 2399,
    rating: 4.91,
    reviewsCount: 43,
    description: "Pastel blush pink tall cake featuring edible wafer butterflies, hand-piped meringue roses, and delicate pearl beads.",
    shortDesc: "Pastel Blush Cake with Edible Wafer Butterflies & Spun Sugar Pearls.",
    category: "Baby Shower",
    eggless: true,
    flavors: ["Classic Vanilla Bean", "Strawberries & Cream", "Peach Mango Chantilly"],
    weights: ["1 kg", "2 kg"],
    images: [
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["New"],
    isFeatured: false,
    isBestSeller: false,
    ingredients: ["Organic Flour", "Vanilla Beans", "Wafer Paper", "Sugar Pearls"],
    stock: true,
  },
  {
    id: "cake-8",
    name: "Luxury French Macaron Box (Set of 12)",
    slug: "luxury-french-macaron-box",
    price: 1299,
    offerPrice: 1099,
    rating: 4.96,
    reviewsCount: 215,
    description: "Assorted box of 12 signature Parisian macarons: 24K Gold Dark Truffle, Rose Raspberry, Salted Caramel, Pistachio, Earl Grey, and Passionfruit.",
    shortDesc: "Box of 12 handcrafted French macarons in signature velvet box.",
    category: "Cupcakes & Mini Bites",
    eggless: false,
    flavors: ["Assorted French Flavors"],
    weights: ["Box of 12"],
    images: [
      "https://images.unsplash.com/photo-1603532648955-039310d9ed75?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=1000&q=80",
    ],
    tags: ["Best Seller"],
    isFeatured: true,
    isBestSeller: true,
    ingredients: ["Almond Powder", "Egg White Meringue", "Valrhona Chocolate", "Fruit Purees"],
    stock: true,
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    customerName: "Ananya Roy",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    date: "August 2, 2026",
    comment: "Sonicas Bake crafted our wedding cake and it was absolute perfection! The 24K gold leaf detailing looked like a piece of art straight from Ladurée in Paris. Our guests couldn't stop raving about the Belgian Dark Truffle flavor!",
    cakeName: "The Royal 24K Gold Crown",
    verifiedBuyer: true,
  },
  {
    id: "rev-2",
    customerName: "Vikramaditya Sharma",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    date: "July 28, 2026",
    comment: "Ordered the Golden Ferrero Hazelnut cake for my wife's 30th birthday. The custom cake booking process was seamless, delivery arrived exactly on time in a temperature-controlled luxury box, and the taste was 10/10!",
    cakeName: "Golden Ferrero Hazelnut Elegance",
    verifiedBuyer: true,
  },
  {
    id: "rev-3",
    customerName: "Dr. Meera Kapoor",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    date: "July 15, 2026",
    comment: "As someone who is very picky about eggless cakes, Sonicas Bake exceeded every single expectation. Moisture level, rich cocoa intensity, and delicate floral aesthetics were unmatched. 100% my go-to bakery now.",
    cakeName: "Velvet Rose & Champagne Symphony",
    verifiedBuyer: true,
  },
];

export const COUPONS: Coupon[] = [
  {
    code: "SONICA10",
    discountPercent: 10,
    minOrderValue: 1500,
    description: "Get 10% off on orders above ₹1,500",
  },
  {
    code: "LUXURY20",
    discountPercent: 20,
    minOrderValue: 3000,
    description: "Get 20% off on orders above ₹3,000",
  },
  {
    code: "FIRSTGOLD",
    discountFlat: 500,
    minOrderValue: 2500,
    description: "Flat ₹500 OFF on your first luxury order",
  },
];
